name: Deploy Function App (Container) - dev

on:
  push:
    branches: [ main ]

permissions:
  id-token: write
  contents: read

env:
  AZURE_ENV_NAME: dev
  AZURE_LOCATION: eastus2
  IMAGE_NAME: document-extractor-func
  IMAGE_TAG: ${{ github.sha }}

jobs:
  deploy:
    environment: dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate OIDC inputs
        shell: bash
        run: |
          missing=()
          [ -z "${{ secrets.AZURE_CLIENT_ID }}" ] && missing+=(AZURE_CLIENT_ID)
          [ -z "${{ secrets.AZURE_TENANT_ID }}" ] && missing+=(AZURE_TENANT_ID)
          [ -z "${{ secrets.AZURE_SUBSCRIPTION_ID }}" ] && missing+=(AZURE_SUBSCRIPTION_ID)
          if [ ${#missing[@]} -ne 0 ]; then
            echo "Required GitHub secrets are missing for OIDC login: ${missing[*]}" 1>&2
            echo "Add these as environment secrets on the 'dev' environment (or repo-level secrets) and re-run." 1>&2
            exit 1
          fi

      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Ensure resource providers are registered
        shell: bash
        run: |
          set -e
          for rp in Microsoft.Web Microsoft.ContainerRegistry Microsoft.Insights Microsoft.ManagedIdentity Microsoft.Storage; do
            az provider register --namespace $rp --wait
          done

      - name: Install jq
        shell: bash
        run: |
          sudo apt-get update -y
          sudo apt-get install -y jq

      - name: Verify Azure principal
        id: whoami
        shell: bash
        env:
          EXPECTED_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        run: |
          set -e
          # Show current account and principal (safe)
          az account show --query '{name:name, id:id, tenantId:tenantId, user:user}' -o json
          # Extract the logged-in principal clientId (for service principals, user.name is the clientId)
          CURRENT_CLIENT_ID=$(az account show --query 'user.name' -o tsv || true)
          if [ -z "$CURRENT_CLIENT_ID" ]; then
            echo "Could not determine logged-in principal" 1>&2
            exit 1
          fi
          if [ "$CURRENT_CLIENT_ID" != "$EXPECTED_CLIENT_ID" ]; then
            echo "Logged in as unexpected client-id: $CURRENT_CLIENT_ID" 1>&2
            echo "Fix: Update AZURE_CLIENT_ID secret to the correct App (the one with federated credential and role assignments), or grant this principal Contributor on the subscription/RG." 1>&2
            exit 1
          fi

      - name: Resolve subscription and resource group
        id: rg
        shell: bash
        run: |
          SUB_ID=$(az account show --query id -o tsv)
          echo "sub_id=$SUB_ID" >> $GITHUB_OUTPUT
          # create RG if not exists
          RG_NAME=rg-doc-extractor-func-${AZURE_ENV_NAME}
          az group create -n $RG_NAME -l ${AZURE_LOCATION}
          echo "rg_name=$RG_NAME" >> $GITHUB_OUTPUT

      - name: Deploy infra (Bicep)
        id: bicep
        run: |
          set -e
          az deployment group create \
            -g ${{ steps.rg.outputs.rg_name }} \
            -n functionapp \
            -f infra/functionapp.bicep \
            -p @infra/functionapp.parameters.json \
            -p location=${AZURE_LOCATION} environmentName=${AZURE_ENV_NAME}
          # verify deployment success
          STATE=$(az deployment group show -g ${{ steps.rg.outputs.rg_name }} -n functionapp --query properties.provisioningState -o tsv || echo "")
          if [ "$STATE" != "Succeeded" ]; then
            echo "Deployment did not succeed (state=$STATE). Showing operations..." 1>&2
            az deployment operation group list -g ${{ steps.rg.outputs.rg_name }} -n functionapp -o table || true
            exit 1
          fi
          # capture outputs
          ACR_SERVER=$(az deployment group show -g ${{ steps.rg.outputs.rg_name }} -n functionapp --query properties.outputs.ACR_LOGIN_SERVER.value -o tsv || true)
          FUNC_NAME=$(az deployment group show -g ${{ steps.rg.outputs.rg_name }} -n functionapp --query properties.outputs.FUNCTION_APP_NAME.value -o tsv || true)
          UAMI_ID=$(az deployment group show -g ${{ steps.rg.outputs.rg_name }} -n functionapp --query properties.outputs.UAMI_ID.value -o tsv || true)
          if [ -z "$FUNC_NAME" ]; then
            # Fallback: find any function app in the RG
            FUNC_NAME=$(az resource list -g ${{ steps.rg.outputs.rg_name }} --resource-type Microsoft.Web/sites --query "[?contains(kind, 'functionapp')].name | [0]" -o tsv || true)
          fi
          echo "acr_login_server=$ACR_SERVER" >> $GITHUB_OUTPUT
          echo "func_name=$FUNC_NAME" >> $GITHUB_OUTPUT
          echo "uami_id=$UAMI_ID" >> $GITHUB_OUTPUT

      - name: Wait for Function App resource
        shell: bash
        run: |
          set -e
          FUNC_NAME=${{ steps.bicep.outputs.func_name }}
          if [ -z "$FUNC_NAME" ]; then
            FUNC_NAME=$(az functionapp list -g ${{ steps.rg.outputs.rg_name }} --query "[0].name" -o tsv)
          fi
          if [ -z "$FUNC_NAME" ]; then
            echo "Function App name not found after deployment." 1>&2
            az functionapp list -g ${{ steps.rg.outputs.rg_name }} -o table || true
            exit 1
          fi
          echo "Ensuring Function App $FUNC_NAME is started and ready..."
          # Try to start it (no-op if already running)
          az functionapp start -g ${{ steps.rg.outputs.rg_name }} -n "$FUNC_NAME" >/dev/null 2>&1 || true
          # Wait up to ~5 minutes
          for i in {1..30}; do
            STATE=$(az functionapp show -g ${{ steps.rg.outputs.rg_name }} -n "$FUNC_NAME" --query "state" -o tsv 2>/dev/null || true)
            PROV=$(az functionapp show -g ${{ steps.rg.outputs.rg_name }} -n "$FUNC_NAME" --query "properties.provisioningState" -o tsv 2>/dev/null || true)
            echo "Attempt $i: state=$STATE provisioningState=$PROV"
            if [ "$PROV" = "Succeeded" ] || [ "$STATE" = "Running" ]; then
              echo "Function App is ready: state=$STATE provisioningState=$PROV"
              break
            fi
            sleep 10
          done
          # Proceed even if not fully running; next steps will set container and restart

      - name: Get ACR login server
        id: acr
        run: |
          ACR_SERVER=${{ steps.bicep.outputs.acr_login_server }}
          if [ -z "$ACR_SERVER" ]; then
            ACR_SERVER=$(az acr list --resource-group ${{ steps.rg.outputs.rg_name }} --query "[0].loginServer" -o tsv)
          fi
          if [ -z "$ACR_SERVER" ]; then
            echo "ACR login server not found. Check deployment outputs and that ACR exists in the resource group." 1>&2
            az acr list --resource-group ${{ steps.rg.outputs.rg_name }} -o table || true
            exit 1
          fi
          echo "login_server=$ACR_SERVER" >> $GITHUB_OUTPUT

      - name: Verify AcrPull role assignment (UAMI -> ACR)
        run: |
          set -e
          rg=${{ steps.rg.outputs.rg_name }}
          ACR_NAME=$(echo ${{ steps.acr.outputs.login_server }} | cut -d. -f1)
          ACR_ID=$(az acr show -n "$ACR_NAME" -g "$rg" --query id -o tsv)
          UAMI_ID=${{ steps.bicep.outputs.uami_id }}
          UAMI_PRINCIPAL_ID=$(az resource show --ids "$UAMI_ID" --query properties.principalId -o tsv)
          echo "Waiting for AcrPull role on $ACR_NAME for principal $UAMI_PRINCIPAL_ID..."
          ok=0
          for i in {1..30}; do
            COUNT=$(az role assignment list --assignee-object-id "$UAMI_PRINCIPAL_ID" --role "AcrPull" --scope "$ACR_ID" --query "length(@)" -o tsv)
            echo "Attempt $i: assignments=$COUNT"
            if [ "$COUNT" != "0" ] && [ -n "$COUNT" ]; then
              ok=1; break
            fi
            sleep 10
          done
          if [ "$ok" -ne 1 ]; then
            echo "Warning: AcrPull not confirmed yet; continuing (RBAC propagation can take several minutes)." 1>&2
            az role assignment list --assignee-object-id "$UAMI_PRINCIPAL_ID" --scope "$ACR_ID" -o table || true
          fi

      - name: Build and push image
        run: |
          az acr login --name $(echo ${{ steps.acr.outputs.login_server }} | cut -d. -f1)
          IMAGE=${{ steps.acr.outputs.login_server }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          docker build -f Dockerfile.functions -t $IMAGE .
          docker push $IMAGE

      - name: Update Function App to new image (PATCH preserve ACR MI)
        run: |
          set -e
          FUNC_NAME=${{ steps.bicep.outputs.func_name }}
          if [ -z "$FUNC_NAME" ]; then
            FUNC_NAME=$(az functionapp list -g ${{ steps.rg.outputs.rg_name }} --query "[0].name" -o tsv)
          fi
          if [ -z "$FUNC_NAME" ]; then
            echo "Function App name not found. Check deployment outputs and RG contents." 1>&2
            az functionapp list -g ${{ steps.rg.outputs.rg_name }} -o table || true
            exit 1
          fi
          IMAGE="DOCKER|${{ steps.acr.outputs.login_server }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}"
          UAMI_ID=${{ steps.bicep.outputs.uami_id }}
          rg=${{ steps.rg.outputs.rg_name }}
          BODY=$(jq -n --arg img "$IMAGE" --arg uami "$UAMI_ID" '{properties:{linuxFxVersion:$img, acrUseManagedIdentityCreds:true, acrUserManagedIdentityID:$uami}}')
          az rest \
            --method patch \
            --uri "https://management.azure.com/subscriptions/${{ steps.rg.outputs.sub_id }}/resourceGroups/$rg/providers/Microsoft.Web/sites/$FUNC_NAME/config/web?api-version=2022-09-01" \
            --headers Content-Type=application/json \
            --body "$BODY"
          az functionapp restart -g $rg -n $FUNC_NAME

      - name: Retry start after image update
        run: |
          set +e
          rg=${{ steps.rg.outputs.rg_name }}
          FUNC_NAME=${{ steps.bicep.outputs.func_name }}
          if [ -z "$FUNC_NAME" ]; then
            FUNC_NAME=$(az functionapp list -g "$rg" --query "[0].name" -o tsv)
          fi
          for i in {1..6}; do
            echo "Restart attempt $i..."
            az functionapp restart -g "$rg" -n "$FUNC_NAME" >/dev/null 2>&1
            sleep 10
          done

      - name: Verify container config
        run: |
          set +e
          rg=${{ steps.rg.outputs.rg_name }}
          sub=${{ steps.rg.outputs.sub_id }}
          FUNC_NAME=${{ steps.bicep.outputs.func_name }}
          if [ -z "$FUNC_NAME" ]; then
            FUNC_NAME=$(az resource list -g "$rg" --resource-type Microsoft.Web/sites --query "[?contains(kind, 'functionapp')].name | [0]" -o tsv || true)
          fi
          if [ -z "$FUNC_NAME" ]; then
            echo "Function App name not found for verification." 1>&2
            az resource list -g "$rg" --resource-type Microsoft.Web/sites -o table || true
            exit 0
          fi
          # Ensure the site exists (non-fatal)
          az resource show -g "$rg" --resource-type Microsoft.Web/sites -n "$FUNC_NAME" -o none 2>/dev/null || true
          # Read config via REST with retries
          URI="https://management.azure.com/subscriptions/$sub/resourceGroups/$rg/providers/Microsoft.Web/sites/$FUNC_NAME/config/web?api-version=2022-09-01"
          success=0
          for i in {1..12}; do
            echo "Fetch web config attempt $i..."
            az rest --method get --uri "$URI" --output json >/tmp/webcfg.json 2>/dev/null
            if [ $? -eq 0 ]; then
              cat /tmp/webcfg.json | jq -r '.properties | {linuxFxVersion, acrUseManagedIdentityCreds, acrUserManagedIdentityID}'
              success=1
              break
            fi
            sleep 10
          done
          if [ $success -ne 1 ]; then
            echo "Warning: web config not yet available; continuing" 1>&2
            az functionapp show -g "$rg" -n "$FUNC_NAME" -o table || true
          fi

      - name: Output URL
        run: |
          FUNC_NAME=${{ steps.bicep.outputs.func_name }}
          if [ -z "$FUNC_NAME" ]; then
            FUNC_NAME=$(az functionapp list -g ${{ steps.rg.outputs.rg_name }} --query "[0].name" -o tsv)
          fi
          echo "https://$FUNC_NAME.azurewebsites.net"
